### ISSUE TITLE
Regarding logo

### ISSUE THREAD

**Issue by somebee** [imba/branding-imba#1]
Hey. Amazing work by @iamtirado on the coming Imba brand. Regarding the logo, I somewhat like the first suggestion where the I has a dot, so it looks more like a flying human / creature.

![](https://user-images.githubusercontent.com/13579055/48960626-eeda2380-ef22-11e8-9428-cc6f8dddacb1.png)
)

What do you guys think?

**Comment by aalemayhu** [comment]
The current logo looks good, assuming this issue is outdated since the logo was updated in f22459b2e1f7 (Updated logo on Readme, 2019-01-08). Please reopen if that is not the case.
